import {MatButtonModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatInputModule,
    MatDialogModule,
    MatIconModule,
    MatListModule,
    MatMenuModule,
    MatSnackBarModule,
    MatButtonToggleModule,
    MatProgressSpinnerModule,
    MatSidenavModule,
    MatGridListModule,
    MatToolbarModule,
    MatSelectModule,
    MatTabsModule,
    MatExpansionModule,
    MatCardModule,
    MatDatepickerModule,
    MatTableModule,
    MatPaginatorModule,
    MatStepperModule,
    MatNativeDateModule,
    MatChipsModule

} from '@angular/material';

export const MaterialModule = [
    MatButtonModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatInputModule,
    MatDialogModule,
    MatIconModule,
    MatListModule,
    MatMenuModule,
    MatSnackBarModule,
    MatButtonToggleModule,
    MatProgressSpinnerModule,
    MatSidenavModule,
    MatGridListModule,
    MatToolbarModule,
    MatSelectModule,
    MatTabsModule,
    MatExpansionModule,
    MatCardModule,
    MatDatepickerModule,
    MatTableModule,
    MatPaginatorModule,
    MatStepperModule,
    MatNativeDateModule,
    MatChipsModule
];
