export interface Postjob{
    key?:string;
    company_key?:string;
    category_key?:string;
    jobtitle?:string;
    exp:number;
    hiring:number;
    salary:string;
    gender:string;
    age:string;
    postdate?:Date;
    expdate?:Date;
    term:string;
    industry:string;
    qualification:string;
    language:string;
    location?:string;
    requirement:string;
    description:string;
}
